### ISSUE TITLE
Commit id corresponding to ROCm1.6 release

### ISSUE THREAD

**Issue by FalconBsp** [RadeonOpenCompute/ROCm-OpenCL-Runtime#10]
We did not see specific tag for ROCm1.6. Can we get details of commit id specific to ROCm1.6 release.

**Comment by FalconBsp** [comment]
Thanks for adding ROCm1.6 tag details.

**Comment by lmoriche** [comment]
The 1.6 manifest should look like this:

<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <remote  name="RadeonOpenCompute" fetch="https://github.com/RadeonOpenCompute/" />
  <remote  name="KhronosGroup" fetch="https://github.com/KhronosGroup/" />

  <default revision="roc-1.6.x"/>

  <project path="opencl" name="ROCm-OpenCL-Runtime" remote="RadeonOpenCompute" />
  <project path="opencl/compiler/llvm" name="llvm" remote="RadeonOpenCompute"/>
  <project path="opencl/compiler/llvm/tools/clang" name="clang" remote="RadeonOpenCompute"/>
  <project path="opencl/compiler/llvm/tools/lld" name="lld" remote="RadeonOpenCompute"/>
  <project path="opencl/library/amdgcn" name="ROCm-Device-Libs" remote="RadeonOpenCompute"/>
  <project path="opencl/compiler/driver" name="ROCm-OpenCL-Driver" remote="RadeonOpenCompute"/>

  <project path="opencl/api/opencl/khronos/icd" name="OpenCL-ICD-Loader" revision="6849f617e991e8a46eebf746df43032175f263b3" remote="KhronosGroup"/>
</manifest>
