### ISSUE TITLE
clinfo ERROR: clBuildProgram(-11)

### ISSUE THREAD

**Issue by tpkessler** [RadeonOpenCompute/ROCm-OpenCL-Runtime#110]
## Problem
clinfo from this package aborts with a clBuildProgram error:
```
$ /opt/rocm/bin/x86_64/clinfo > /dev/null
LoadLib(libhsa-ext-finalize64.so.1) failed: libhsa-ext-finalize64.so.1: cannot open shared object file: No such file or directory
ERROR: clBuildProgram(-11)
```
For the first error message, see my issue [here](https://github.com/RadeonOpenCompute/ROCR-Runtime/issues/89#issue-596359824).

## System
Arch Linux (kernel 5.6.3), compiled ROCm from source.
Output of `rocminfo`: [here](https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/files/4464742/rocminfo.txt)
Output of `clinfo`: [here](https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/files/4464744/clinfo.txt)

**Comment by kode54** [comment]
No opencl using software can find any devices with this package installed, disregarding those unrelated warnings... am I missing a kernel module?

**Comment by helloworld1** [comment]
rocminfo works fine so it doesn't mean missing kernel module kernel 5.6+ should have /dev/kfd.

**Comment by tpkessler** [comment]
I found the source of the error: I compiled the library with `gcc` instead of AMD's `clang` (Lightning Compiler).
