### ISSUE TITLE
OpenCL 2.0 CTS got failure on rocm 3.9 [vega 20]

### ISSUE THREAD

**Issue by qishilu** [RadeonOpenCompute/ROCm-OpenCL-Runtime#129]
hi, guys,

The half_op in OpenCL CTS got failure when  I run on vega20 with rocm 3.9.0 release driver.
the failed subcase is  vloada_half.
Could you help to check it?
log is attached。 

[Half_Ops.txt](https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/files/5686120/Half_Ops.txt)

**Comment by JasonTTang** [comment]
Hi, It's a known issue, due to KFD doesn't report the correct sramecc settings. It's a vega20 specific issue. The device name 'gfx906' implies that sramecc is disabled.
