### ISSUE TITLE
Can RoCm-opencl-runtime  support build objects with clCreateProgramWithBinary runtime API ?

### ISSUE THREAD

**Issue by malixian** [RadeonOpenCompute/ROCm-OpenCL-Runtime#131]
I have intermediate device-agnostic binaries(SPIRV) and I wish to build objects with clCreateProgramWithBinary runtime API . I find this way works from [document](https://rocmdocs.amd.com/en/latest/Programming_Guides/Opencl-programming-guide.html#amd-rocm-implementation). Can RoCm-opencl-runtime support this way?

**Comment by preda** [comment]
AFAIK ROCm OpenCL does not accept SPIRV binary kernels. (It does accept another form of binary kernels though, a form of ELF object code, which is not portable, thus probably not what you want).
