### ISSUE TITLE
latency has 100us？

### ISSUE THREAD

**Issue by qiji2023** [RadeonOpenCompute/ROCm-OpenCL-Runtime#163]
Queue | Submit | <---> | Start | Complete | End | Diff
-- | -- | -- | -- | -- | -- | --
96606369888300 | 96606369893300 | 109140 | 96606370002440 | 96606406652760 | 96606406652760 | -460
96606369891900 | 96606406652300 | 106080 | 96606406758380 | 96606444330270 | 96606444330270 | 130
96606369892900 | 96606444330400 | 104650 | 96606444435050 | 96606482888990 | 96606482888990 | 4810
96606369893900 | 96606482893800 | 111170 | 96606483004970 | 96606521316380 | 96606521316380 | -1880
96606369894600 | 96606521314500 | 103250 | 96606521417750 | 96606559753400 | 96606559753400 |  
  |   |   |   |   |   |  

I tested a program， many kernels on same command queue，start - submit has 100us？ I think the result is very ridiculous！！！！

**Comment by qiji2023** [comment]
Have developers been fired？

**Comment by jlgreathouse** [comment]
No reproducer, description of test scenario, or version information.
