### ISSUE TITLE
Truly Awesome!!

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm-OpenCL-Runtime#2]
Open-source-ing the OpenCL stack is just fantastic - thank you for doing this.
I know this will bring many good things in return to AMD and the entire OpenCL community.

**Comment by gstoner** [comment]
Thank you, for myself and many of my team members this was personal mission to make it happen.    We really are trying to get the broader community engaged with the key solution they need.   We have a lot more to come.

**Comment by boxerab** [comment]
Great, please give everyone a high-five for all of their efforts. Looking forward to more cool stuff.
