### ISSUE TITLE
Build with cmake, build type set to Release :  does this cmake output look correct?

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm-OpenCL-Runtime#25]
In particular, it says that native target x86 not selected. Will this affect performance ?

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Eclipse version is set to 4.3 (Kepler). Adjust CMAKE_ECLIPSE_VERSION if this is wrong.
Native target X86 is not selected; lli will not JIT code
Threads enabled.
Doxygen disabled.
Go bindings disabled.
OCaml bindings disabled, need ctypes >=0.4.
LLVM host triple: x86_64-unknown-linux-gnu
LLVM default target triple: x86_64-unknown-linux-gnu
Building with -fPIC
Constructing LLVMBuild project information
Linker detection: GNU ld
Targeting AMDGPU
Clang version: 6.0.0
LLD version: 6.0.0
Linker detection: GNU ld
Configuring done
Generating done

**Comment by lmoriche** [comment]
Output looks correct. We are not targeting the native CPU with the OpenCL/ROCm compiler toolchain. This will not affect performance.
