### ISSUE TITLE
How to link to project ?

### ISSUE THREAD

**Issue by boxerab** [RadeonOpenCompute/ROCm-OpenCL-Runtime#28]
My opencl program uses `/opt/rocm/opencl/include` include directory and `/opt/rocm/opencl/lib/x86_64/libamdocl64.so`  

If I build the runtime locally, and install in `/usr/local` then how do I link and compile ? 

Only static builds seem to work, btw.

**Comment by lmoriche** [comment]
You link with libOpenCL.so. libamdocl64.so is dynamically loaded by the ICD (libOpenCL.so.1). You can add the path to the runtime you built to ld.so.conf or set LD_LIBRARY_PATH.

**Comment by boxerab** [comment]
Thanks. Will try this next week.
