### ISSUE TITLE
Consuming SPIR-V kernels

### ISSUE THREAD

**Issue by uhrm** [RadeonOpenCompute/ROCm-OpenCL-Runtime#31]
I have some OpenCL kernels in form of SPIR-V binaries that I'm trying to run with ROCm OpenCL. I see that ROCm OpenCL runtime has the extension function `clCreateProgramWithILKHR`. However, I don't see that the ROCm platform announces the `cl_khr_il_program` extension.

Using this function to create a program works without giving an error. Also, I can build programs (`clBuildProgram`) created from the SPIR-V binaries without getting errors. However, when I try to create a kernel (`clCreateKernel`), I get a `CL_INVALID_KERNEL_NAME` error.

My question is: can I execute SPIR-V binary kernels with ROCm OpenCL? And if yes, is there some example code that shows how to build these kernels successfully?

**Comment by gstoner** [comment]
SPIR-V is not supported by the OpenCL Compiler
