### ISSUE TITLE
[RFF] lower-end ROCm supported OpenCL CI testing hardware

### ISSUE THREAD

**Issue by pszi1ard** [RadeonOpenCompute/ROCm-OpenCL-Runtime#32]
Our team is looking into modernizing our ancient AMD OpenCL CI testing hardware. We were considering the RX 550 as these are cheap, consume little power, and are reasonably new being built on Polaris.
However, Phoronix [reported](https://www.phoronix.com/scan.php?page=article&item=amd-rocm16-nvidia&num=1) in July that the RX 550 is not supported in ROCm 1.6. Has this issue been addressed in 1.6.148; if not, is there an ETA for a fix?

Secondly, are there other, reasonably cheap cards that you'd recommend? Long support would be quite desirable, I don't want to wake up in a year that the card is EOL-ed in ROCm, nor would I like to have to distro upgrade too often.

**Comment by gstoner** [comment]
It RX550 is Device ID issue,   I ask the team if this supported now. 

Greg

**Comment by pszi1ard** [comment]
Thanks for the quick feedback! Any thoughts on the support plans for Polaris12? Given that there are no Vega low-end cards, I'd hope ROCm will support recently released Polaris cards for quite some time.

Secondly, under-clocking of Polaris cards is also supported in rocm-smi, right?

**Comment by gstoner** [comment]
RX480 RX470 are supported.

**Comment by gstoner** [comment]
We are working DKMS for REHL and SUSE right now

**Comment by pszi1ard** [comment]
> RX480 RX470 are supported.

Should I take that as implying that RX 550 is not supported? Or that 480 and 470 are good alternatives? Was hoping for <100 W and max $100-150 / card.

**Comment by pszi1ard** [comment]
> We are working DKMS for REHL and SUSE right now

That's great to hear, although we're using Ubuntu LTS releases, so I hope DKMS for at least 16.04 LTS will be available too.

**Comment by gstoner** [comment]
I need to look at Device ID in the base driver.  it really is that simple

**Comment by pszi1ard** [comment]
> I need to look at Device ID in the base driver. it really is that simple

OK, thanks. I'll wait for that feedback.

**Comment by pszi1ard** [comment]
Can you confirm whether RX 550 has been enabled in the last ROCm patch release?

**Comment by gstoner** [comment]
OpenCL is running on RX550 via the AMDGPUpro driver  currently, I dig into this more.

**Comment by pszi1ard** [comment]
Thanks!

**Comment by pinkflozd** [comment]
Hello. Any news on rocm support on RX550? There is no support in AMDGPU-pro either to date for this low power card. So we don't have decent OpenCL support on linux

**Comment by nickbuller** [comment]
Hi, Is there any update on this issue. I have just tried ROCm 1.7 (1.7.137) on 4.13.0-32-generic on a totally clean box and clinfo still reports no devices. This has been working on Windows for ages.

**Comment by pszi1ard** [comment]
Any update on the RX 550? Retail price is now very close to the RX 560 and we've opted for the latter instead of waiting, but I still wonder if there is a reasonable _single-slot_ card that is worth using for CI/testing?

**Comment by jlgreathouse** [comment]
Hi @pszi1ard 

As of the recently ROCm 2.0 release, I believe "Polaris 12" GPUs should work. At least, they work for me now. :)

Note that if you are using an upstream kernel, this support will likely not hit until at least 4.21. The support is sitting in in `amd-staging-drm-next`, but it has not been upstreamed yet. The support is, however, available in our ROCK driver in ROCm 2.0.0.

It should work for OpenCL, HCC, HIP, and anywhere else that gfx803 GPUs work.
