### ISSUE TITLE
Question: FP16 support

### ISSUE THREAD

**Issue by Dekken** [RadeonOpenCompute/ROCm-OpenCL-Runtime#33]
Hey there,

I've been reading that FP16 is not yet available to opencl on VEGA, can you tell me if it is planned and perhaps give me an ETA?

Thanks for your time

regards

**Comment by gstoner** [comment]
We just posted 1.6.4 which support Packed Float16 in OpenCL,  The source code should already be posted for it.

**Comment by Dekken** [comment]
Thanks Greg!

I'll help spread the word.
