### ISSUE TITLE
Viewing generated LLVM IR of OpenCL kernels

### ISSUE THREAD

**Issue by masahi** [RadeonOpenCompute/ROCm-OpenCL-Runtime#38]
Hi, I want to see LLVM IR of OpenCL kernels, generated by clang.
Is there a way to do this easily, without rebuilding an entire driver myself?

I can see LLVM bitcode is generated [here](https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/blob/master/runtime/device/device.cpp#L557). All I want is to somehow  dump the output of this driver call.

I want to do this to compare IR generated by clang, and those generated by [ROCm backend](http://www.tvmlang.org/2017/10/30/Bringing-AMDGPUs-to-TVM-Stack-and-NNVM-Compiler-with-ROCm.html) of TVM.

Thanks.

**Comment by kzhuravl** [comment]
Hi @masahi,

You can export AMD_OCL_BUILD_OPTIONS_APPEND=-save-temps-all and run your OpenCL application as usual. Passing "-save-temps-all" option will cause it dump all intermediate files (including LLVM bitcode) into the current directory. See more here:
  - https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/blob/master/compiler/lib/utils/OPTIONS.def#L963

You can further use llvm-dis to get LLVM IR from LLVM bitcode:
  - llvm-dis your-bitcode-filen.bc

Konstantin

**Comment by masahi** [comment]
@kzhuravl With export AMD_OCL_BUILD_OPTIONS_APPEND=-save-temps-all, I got 
```
_temp_0_fiji.cl 
 _temp_0_fiji.s  
_temp_0_fiji.so
```
but no *.bc code. I'm using opencl runtime from rocm 1.6.3.

Do I need rocm 1.6.4?

**Comment by masahi** [comment]
@kzhuravl [Here](https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/blob/master/compiler/lib/utils/options.hpp#L176), it says bitcode cannot be dumped in a release product?

**Comment by kzhuravl** [comment]
> @kzhuravl Here, it says bitcode cannot be dumped in a release product?

I think this is the case, you are hitting this [line](https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/blob/ea8464aff089a4aea0629dce9ba15c6aaadb4972/compiler/lib/utils/options.cpp#L1384) (SKIP_INTERNAL_OPTION is defined), hence you do not see bitcode dumped. How did you obtain opencl binaries? Did you use apt-get or build them yourself?

I just built both 1.6.3 and 1.6.4 with **cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="AMDGPU;X86" .. ; make**, and when I run opencl applications, I see bitcode dumped using the method described in my previous comment.

**Comment by masahi** [comment]
I installed opencl library with sudo apt-get install rocm rocm-opencl, following the instruction [here](https://github.com/RadeonOpenCompute/ROCm). 

Maybe I should go ahead and buid the runtime myself. Do you have both IRs before and after optimization dumped?

**Comment by masahi** [comment]
ok, looking at the [section](https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/blob/master/runtime/device/rocm/rocprogram.cpp#L769) where optimization and codegen happen, I'm guessing an optimized IR is not dumped.

What should I do, if I want an optimized IR, in addition to an unoptimized IR?

Is it suffice to add something like "-S -O3 -amdgpu-early-inline-all" to the command line option when compiling an opencl kernel with clang?

**Comment by kzhuravl** [comment]
Alternatively you can pass "-print-after-all" option through AMD_OCL_BUILD_OPTIONS_APPEND. "-print-after-all" LLVM option causes it to print LLVM IR after each pass (you will also get MIs after each pass after isel as a bonus).

In order to get this, you should build opencl runtime in debug mode:
- cmake -DCLANG_ENABLE_STATIC_ANALYZER=ON '-DLLVM_TARGETS_TO_BUILD=AMDGPU;X86' -DLLVM_BUILD_TOOLS=ON -DLLVM_INCLUDE_TESTS=ON ..
- make
- export AMD_OCL_BUILD_OPTIONS_APPEND=-Wb,-print-after-all
- Now, when you run your app, LLVM IR after each pass will be printed to stderr, so you can pipe it into a file for better readability:
  - your-opencl-app 2> out.txt

**Comment by masahi** [comment]
@kzhuravl I built the runtime with debug mode, and IR dumping is working! 
I'm getting loads of IRs with -print-after-all :)

Thanks
