### ISSUE TITLE
OpenCL apps fail with memory access fault

### ISSUE THREAD

**Issue by isloven** [RadeonOpenCompute/ROCm-OpenCL-Runtime#41]
Running OpenCL apps such is the Caffe OpenCL branch or Darknet OpenCL branch fail with this error:

"Memory access fault by GPU node-1 on address 0x922801000. Reason: Page not present or supervisor privilege."

This happens on multiple computers running different Vega cards. Note that the vectorcopy and HelloWorld OpenCL test programs work correctly on these systems.

Note that the hipCaffe works on the same hardware, however this seems like a bug and other apps (such is Darknet) do not have a HIP port and therefore this bug should be fixed.

**Comment by gstoner** [comment]
Can you try these steps 
 
sudo –s
echo 0 > /sys/module/amdkfd/parameters/noretry

sudo usermod -a -G video $LOGNAME 

sudo vi /etc/modprobe.d/amdgpu.conf 
options amdgpu vm_update_mode=0
options amdkfd cwsr_enable=0
sudo update-initramfs -u

 Reboot and test

**Comment by isloven** [comment]
Still getting the error with the suggested changes:

Memory access fault by GPU node-1 on address 0x922a03000. Reason: Page not present or supervisor privilege.

Thank you for the help!

**Comment by gstoner** [comment]
Ok I see if SQE is seeing this, what type of system do you have CPU, GPU etc

**Comment by isloven** [comment]
Multiple systems seem to exhibit this issue - so far it can be replicated on Threadripper 1950X, Ryzen 1800X and Core i7-5xxx boxes with various motherboards.

The GPU I am testing this on right now is air cooled Vega Frontier 16GB (i.e. blue card). Also tested on a non-Frontier Vega card and it exhibits the same problem.

**Comment by gstoner** [comment]
Can you point us to where you're picking up OpenCL darknet we trying to do some test.   If there is an issue in Caffe OpenCL itself we need to talk to the developer.   Some time we see out of bound memory reference in the kernel themselves if this happens on ROCm we fail the app, unlike past driver since we now support Guard pages.

**Comment by isloven** [comment]
You can get OpenCL version of darknet from here: 
https://github.com/myestro/darknet.git

The OpenCL enabled Caffe is in the official branch here:
https://github.com/BVLC/caffe/tree/opencl

**Comment by gstoner** [comment]
We have tried darknet-opencl from https://github.com/myestro/darknet.git  and test is running fine. Tried on 3 setups with rocm release 1.7. We are not sure if reporter used anything different then what we have tried.
Also, in the below result, CARROT predication looks like something wrong. In the attached output png, we are not seeing carrot.
 
SETUP1 : 2xVega10 8GB Frontier [LargeBar ] + X99-E WS
SETUP2 : Vega10 16GB Frontier [LargeBar ] + X99-E WS
SETUP3:  2xBaffinXT [ Default VBIOS, Non LargeBar] + ASUS Ryzen 7(1700X) + Motherboard / AMD X370 Chipset
SETUP4 : 2xFijiNano[LargeBar ] + X99-E WS
 
Darknet built with command : make darknet GPU=1 OPENCL=1
Pre-trained weight file used:  https://pjreddie.com/media/files/yolo.weights
Command used to run the test : ./darknet detect cfg/yolo.cfg weights/yolo.weights data/dog.jpg
Output of the command:
$ ./darknet detect cfg/yolo.cfg weights/yolo.weights data/dog.jpg
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  32
    1 max          2 x 2 / 2   416 x 416 x  32   ->   208 x 208 x  32
    2 conv     64  3 x 3 / 1   208 x 208 x  32   ->   208 x 208 x  64
    3 max          2 x 2 / 2   208 x 208 x  64   ->   104 x 104 x  64
    4 conv    128  3 x 3 / 1   104 x 104 x  64   ->   104 x 104 x 128
    5 conv     64  1 x 1 / 1   104 x 104 x 128   ->   104 x 104 x  64
    6 conv    128  3 x 3 / 1   104 x 104 x  64   ->   104 x 104 x 128
    7 max          2 x 2 / 2   104 x 104 x 128   ->    52 x  52 x 128
    8 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256
    9 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128
   10 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256
   11 max          2 x 2 / 2    52 x  52 x 256   ->    26 x  26 x 256
   12  conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512
   13 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256
   14 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512
   15 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256
   16 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512
   17 max          2 x 2 / 2    26 x  26 x 512   ->    13 x  13 x 512
   18 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   19 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512
   20 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   21 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512
   22  conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   23 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   24 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   25 route  16
   26 conv     64  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x  64
   27 reorg              / 2    26 x  26 x  64   ->    13 x  13 x 256
   28 route  27 24
   29 conv   1024  3 x 3 / 1    13 x  13 x1280   ->    13 x  13 x1024
   30 conv    425  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 425
   31 detection
Setup: net.n = 32
net.layers[0].batch = 8
Loading weights from weights/yolo.weights...mj = 0, mn = 1, *(net->seen) = 32013312
load_convolutional_weights: l.n*l.c*l.size*l.size = 864
load_convolutional_weights: l.n*l.c*l.size*l.size = 18432
load_convolutional_weights: l.n*l.c*l.size*l.size = 73728
load_convolutional_weights: l.n*l.c*l.size*l.size = 8192
load_convolutional_weights: l.n*l.c*l.size*l.size = 73728
load_convolutional_weights: l.n*l.c*l.size*l.size = 294912
load_convolutional_weights: l.n*l.c*l.size*l.size = 32768
load_convolutional_weights: l.n*l.c*l.size*l.size = 294912
load_convolutional_weights: l.n*l.c*l.size*l.size = 1179648
load_convolutional_weights: l.n*l.c*l.size*l.size = 131072
load_convolutional_weights: l.n*l.c*l.size*l.size = 1179648
load_convolutional_weights: l.n*l.c*l.size*l.size = 131072
load_convolutional_weights: l.n*l.c*l.size*l.size = 1179648
load_convolutional_weights: l.n*l.c*l.size*l.size = 4718592
load_convolutional_weights: l.n*l.c*l.size*l.size = 524288
load_convolutional_weights: l.n*l.c*l.size*l.size = 4718592
load_convolutional_weights: l.n*l.c*l.size*l.size = 524288
load_convolutional_weights: l.n*l.c*l.size*l.size = 4718592
load_convolutional_weights: l.n*l.c*l.size*l.size = 9437184
load_convolutional_weights: l.n*l.c*l.size*l.size = 9437184
load_convolutional_weights: l.n*l.c*l.size*l.size = 32768
load_convolutional_weights: l.n*l.c*l.size*l.size = 11796480
load_convolutional_weights: l.n*l.c*l.size*l.size = 435200
Done!
test_detector: layers = 13, 13, 5
data/dog.jpg: Predicted in 0.552594 seconds.
pottedplant: 27%
truck: 74%
dog: 81%
bicycle: 83%
carrot: 2498%
Not compiled with OpenCV, saving to predictions.png instead
