### ISSUE TITLE
Availibility of v1.7.1 in Ubuntu repos

### ISSUE THREAD

**Issue by anoother** [RadeonOpenCompute/ROCm-OpenCL-Runtime#52]
Is there a plan for the latest releases to be added to the deb repo at repo.radeon.com/rocm/apt/debian/?

It seemes that v1.7.1 has been released in source form some days ago, but builds do not seem to be available in the repo.

**Comment by jlgreathouse** [comment]
Hi @anoother ,

Thanks for reporting this -- for reference, however, bug reports on ROCm releases should likely go into the issue tracker for ROCm at https://github.com/RadeonOpenCompute/ROCm/issues . Our engineers that handle ROCm releases watch that tracker much more closely than this one.

In any case, the version of ROCm that you see in the deb repo you linked should be 1.7.1. There was a naming issue in the version line that we are working to fix, but the actual binary files should be 1.7.1.

**Comment by anoother** [comment]
Thanks. Will raise an issue in the correct repo if this is still an issue.
