### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Dekken** [RadeonOpenCompute/ROCm-OpenCL-Runtime#55]
Can I get a comment from you guys on this?

Referencing:
https://www.reddit.com/r/OpenCL/comments/8qjwi6/amd_silently_deprecated_app_sdk_opencl/

Is there any plan from AMD to have openCL support on windows?

Thanks

**Comment by gstoner** [comment]
OpenCL on Windows, LinuxPro and ROCm are secure.   OpenCL SDK has nothing to do with OpenCL support on these drivers.  I read the thread yet another example internet making up information that not real.  GPUopen is now where RTG is posting it SDK,  also on Linux we trying to make so you do not need SDK to do development work it just works.    It is not deprecated it the current SDK on Github for Windows driver.

**Comment by Dekken** [comment]
Thanks @gstoner

**Comment by ingframin** [comment]
But then where are the OpenCL headers on Windows?

**Comment by ekondis** [comment]
I guess you can find them here (both headers & libraries):

[https://github.com/GPUOpen-LibrariesAndSDKs/OCL-SDK/releases](https://github.com/GPUOpen-LibrariesAndSDKs/OCL-SDK/releases)
