### ISSUE TITLE
Running precompiled GCN programs

### ISSUE THREAD

**Issue by Naghasan** [RadeonOpenCompute/ROCm-OpenCL-Runtime#60]
Hi,

I'm trying to run a statically compiled OpenCL program, but I get an error "Error while Codegen phase: the binary is incomplete", which comes from here https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/blob/8bfdf45be3ae6b2a774c7b6235927bcab73f4cda/runtime/device/rocm/rocprogram.cpp#L1048

In short, I'm compiling my kernel using clang
`clang -target amdgcn-amd-amdhsa-opencl -mcpu=fiji -O1 ker.cl -o ker.obj`
(The kernel doesn't use any OpenCL builtin, the used GPU is a fiji one)

At runtime, the program is built using `clCreateProgramWithBinary` and `clBuildProgram` (I don't pass any flag). The call to `clBuildProgram` fails with the error mentioned above.

From what I could investigate, it seems that the runtime understand the given binary is a GCN object but don't know what to do with it.

Am I missing a build step or a flag for one of the cl function ?

**Comment by jlgreathouse** [comment]
A couple of questions and a recommendation:
- Which version of Clang are you using to do this compilation?
- Are you sure that yo'ure reading in the entire binary as written out by clang? This may sound like a simple question, but it's worth checking.

As for my recommendation: you may want to compile your statically-built kernels with our [clang-ocl](https://github.com/RadeonOpenCompute/clang-ocl) scripts. We specifically built these to set all the appropriate targets and flags to create binary kernels that one can load with `clBuildProgramWithBinary()`. We do this in MIOpen, for instance. This package is available in our ROCm repos as `rocm-clang-ocl`.

For instance, I just made a quick test program and build the static kernel with:
`clang-ocl ./kernel.cl -mcpu=gfx900 -o $(pwd)/vega10.o`

I then loaded this binary with `clCreateProgramWithBinary()` and it worked properly.

If you're building for Fiji, you may instead want to use `-mcpu=gfx803` as an input. Also note that this script will build with `-cl-std=CL1.2 -D__OPENCL_VERSION__=120`. That said, clang-ocl is just a simple script that sets the proper flags for the version of clang that ships with our OpenCL runtime. You can open it up and see what flags it's using and change them to meet your own needs if you want.

**Comment by Naghasan** [comment]
Thanks for the suggestion, to answer your questions, I'm using clang 6 and the binary is entirely loaded.

I tried with the script and worked fine. My issue was that my build procedure did not include the call to lld.

I actually invoke clang with -c, which I forgot to add when opening the issue, so that was the problem.

Thanks for the help.
