### ISSUE TITLE
rocm opencl cpu support

### ISSUE THREAD

**Issue by tbetcke** [RadeonOpenCompute/ROCm-OpenCL-Runtime#65]
Hi,

I have installed rocm on Ubuntu 18.04.1. My two Radeon WX Pro accords are recognized fine by the rocm OpenCL icd driver. But the CPU is not listed. Is there no Rocm OpenCL CPU support or am I missing something?

Best wishes

Timo

**Comment by jlgreathouse** [comment]
Hi @tbetcke 

You are correct, the ROCm OpenCL runtime does not support CPU targets.
