### ISSUE TITLE
Which OpenCL driver should I choose for Ryzen 5 2400g?

### ISSUE THREAD

**Issue by ghostplant** [RadeonOpenCompute/ROCm-OpenCL-Runtime#66]
I am running Ubuntu 18.10 with Linux Kernel 4.18 so the Ryzen 5 2400g driver should be expected to get integrated by kernel. However, I tried some ways to enable the OpenCL backend for Ryzen 5 2400g but all failed.

Due to hardly any documentation found for this, does anyone know the correct way or documentation to enable OpenCL for this APU? like which one should I choose: OpenCL provided by `amdgpu-pro`, or OpenCL provided by `amd app sdk 3.0`, or OpenCL provided by `rocm-opencl`?

**Comment by jlgreathouse** [comment]
This is a [duplicate issue](https://github.com/RadeonOpenCompute/ROCm/issues/692).
