### ISSUE TITLE
Refs/tags for 3.0 missing?

### ISSUE THREAD

**Issue by justxi** [RadeonOpenCompute/ROCm-OpenCL-Runtime#98]
Hi,

running "repo init -u https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime.git -b roc-3.0.x -m opencl.xml" followed by "repo sync" complains about missing reference.
(https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/blob/roc-3.0.x/opencl.xml)

Or is the https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/blob/master/README.md not up-to-date?

**Comment by shibe2** [comment]
There is [roc-ocl-3.0.x](https://github.com/RadeonOpenCompute/llvm-project/tree/roc-ocl-3.0.x) branch and [roc-ocl-3.0.0](https://github.com/RadeonOpenCompute/llvm-project/tree/roc-ocl-3.0.0) tag in "llvm-project" repository, which apparently replaces old "llvm", "clang", "lld" repositories. I managed to build ROCm-OpenCL-Runtime roc-3.0.0, but it required some hacking. To avoid headache, use previous version of ROCm.

**Comment by justxi** [comment]
I managed to build ROCm-OpenCL-Runtime 3.0.0 in the meantime too, using roc-ocl-3.0.0 from "llvm-project". As you said, it needs some extra work, simply downloading from the git repository does not work for me.

**Comment by ranisalt** [comment]
@shibe2

> I managed to build ROCm-OpenCL-Runtime roc-3.0.0, but it required some hacking.

Did you manage to get past an error of missing CMake files? If so, how? I can't get past it no matter what I try.

**Comment by justxi** [comment]
I built it on Gentoo Linux. The install scripts "ebuilds" are now in Gentoo portage. Or you can find them here:

https://github.com/justxi/rocm/tree/fd074dfcb523d6787ce59adfc198542727fb324a

Look in "dev-libs", "dev-util" and "sys-devel" to find the components.

**Comment by shibe2** [comment]
@ranisalt Maybe you need to install [rocm-cmake](https://github.com/RadeonOpenCompute/rocm-cmake).
